from .libros import Libro as LibroResources
from .libros import Libros as LibrosResources
from .prestamo import Prestamo as PrestamoResources
from .prestamo import Prestamos as PrestamosResources
from .login import Login as LoginResources
from .login import Signup as SignupResources
from .usuarios import Usuario as UsuarioResource
from .usuarios import Usuarios as UsuariosResource
from .notificacion import Notificacion as NotificacionResources
from .valoracion import Valoracion as ValoracionResources
from .valoracion import Valoraciones as ValoracionesResources
from .configuracion import Configuracion as ConfiguracionResources
from .autores import Autor as AutorResources
from .autores import Autores as AutoresResources