from .libros import Libro as LibroResources
from .libros import Libros as LibrosResources
from .prestamo import Prestamo as PrestamoResources
from .prestamo import Prestamos as PrestamosResources
from .login import Login as LoginResources
from .usuarios import Usuario as UsuarioResource
from .usuarios import Usuarios as UsuariosResource
from .notificacion import Notificacion as NotificacionResources
from .comentario import Comentarios as ComentariosResources
from .valoracion import Valoracion as ValoracionResources
from .configuracion import Configuracion as ConfiguracionResources